name: Build Tomcat

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out tomcatData.xml
      uses: actions/checkout@v2

    - name: List of project files and java version
      run: |
          ls -ltr
          java -version

    - name: Check out Apache Tomcat
      uses: actions/checkout@v2
      with:
        repository: astroPhoenix35/github-actions-course-template
        ref: master
        path: ./github-actions-course-template

    - name: Setup Java 9
      uses: actions/setup-java@v1
      with:
        java-version: '9.0.4'
        java-package: jdk
        architecture: x64

    - name: List project files and java version
      run: |
          ls -ltr
          java -version

    - name: Copy Tomcat users into configuration directory
      run: cp -v tomcatData.xml ./github
      
